import { File } from "../types/index";

export const fileSys: File[] = [
  {
    id: 1,
    title: "Welcome",
    content: "",
    date_created: new Date("03/20/23").toISOString(),
    last_modified: new Date("03/24/23").toISOString(),
    is_folder: false,
  },
  {
    id: 2,
    title: "About Me",
    content: "",
    date_created: new Date("03/20/23").toISOString(),
    last_modified: new Date("03/20/23").toISOString(),
    is_folder: false,
  },
  {
    id: 3,
    title: "Documentation",
    date_created: new Date("03/21/23").toISOString(),
    last_modified: new Date("03/21/23").toISOString(),
    is_folder: true,
  },
  {
    id: 4,
    parent: 3,
    title: "Bugs",
    content: "",
    date_created: new Date("04/09/23").toISOString(),
    last_modified: new Date("04/09/23").toISOString(),
    is_folder: false,
  },
  {
    id: 5,
    parent: 3,
    title: "Practical Recursion",
    content: "",
    date_created: new Date("03/21/23").toISOString(),
    last_modified: new Date("03/24/23").toISOString(),
    is_folder: false,
  },
  {
    id: 6,
    parent: 3,
    title: "Feature Overview",
    content: "",
    date_created: new Date("03/21/23").toISOString(),
    last_modified: new Date("03/22/23").toISOString(),
    is_folder: false,
  },
  {
    id: 7,
    parent: 3,
    title: "Features",
    date_created: new Date("03/21/23").toISOString(),
    last_modified: new Date("03/22/23").toISOString(),
    is_folder: true,
  },
  {
    id: 8,
    parent: 7,
    title: "Markdown Preview",
    content: "",
    date_created: new Date("03/22/23").toISOString(),
    last_modified: new Date("03/22/23").toISOString(),
    is_folder: false,
  },
];
